version: '3.8'

services:
  db:
    image: postgres:15
    container_name: transaction-service-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transaction-service
    ports:
      - "5434:5432"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-service-app
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transaction-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - API_KEY=api-key
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge